version: '3.8'

services:
  music-api:
    image: davidkms/music-api
    container_name: nest-music-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # 如果有其他环境变量，可以在这里添加
      # - DATABASE_URL=
      # - JWT_SECRET=
    volumes:
      # 如果需要持久化存储一些数据，可以添加卷挂载
      - ./logs:/app/logs
    networks:
      - music-network
    # 如果需要等待其他服务（如数据库）启动，可以添加 depends_on
    # depends_on:
    #   - postgres

networks:
  music-network:
    driver: bridge